# AUTO-GENERATED by scripts/gen_error_codes.py from ahimsa's
# error-codes.yaml. DO NOT EDIT — regenerate from the YAML source.
"""Typed error-code constants for ahimsa (AHIMSA)."""

COMPONENT = 'AHIMSA'
SUPPORTED_LOCALES = ['en']

AHIMSA_RECIPE_001 = 'AHIMSA-RECIPE-001'
AHIMSA_RECIPE_002 = 'AHIMSA-RECIPE-002'
AHIMSA_RECIPE_003 = 'AHIMSA-RECIPE-003'
AHIMSA_RECIPE_004 = 'AHIMSA-RECIPE-004'
AHIMSA_APP_001 = 'AHIMSA-APP-001'
AHIMSA_APP_002 = 'AHIMSA-APP-002'
AHIMSA_APP_003 = 'AHIMSA-APP-003'
AHIMSA_APP_004 = 'AHIMSA-APP-004'
AHIMSA_MATIKA_001 = 'AHIMSA-MATIKA-001'
AHIMSA_MATIKA_002 = 'AHIMSA-MATIKA-002'
AHIMSA_PLUG_001 = 'AHIMSA-PLUG-001'
AHIMSA_PLUG_002 = 'AHIMSA-PLUG-002'
AHIMSA_PLUG_003 = 'AHIMSA-PLUG-003'
AHIMSA_RESOLVE_001 = 'AHIMSA-RESOLVE-001'
AHIMSA_RESOLVE_002 = 'AHIMSA-RESOLVE-002'
AHIMSA_RESOLVE_003 = 'AHIMSA-RESOLVE-003'
AHIMSA_RESOLVE_004 = 'AHIMSA-RESOLVE-004'
AHIMSA_RESOLVE_005 = 'AHIMSA-RESOLVE-005'
AHIMSA_RESOLVE_006 = 'AHIMSA-RESOLVE-006'
AHIMSA_RESOLVE_007 = 'AHIMSA-RESOLVE-007'
AHIMSA_RESOLVE_008 = 'AHIMSA-RESOLVE-008'
AHIMSA_RESOLVE_009 = 'AHIMSA-RESOLVE-009'
AHIMSA_RELEASE_001 = 'AHIMSA-RELEASE-001'
AHIMSA_RELEASE_002 = 'AHIMSA-RELEASE-002'
AHIMSA_RELEASE_003 = 'AHIMSA-RELEASE-003'
AHIMSA_RELEASE_004 = 'AHIMSA-RELEASE-004'
AHIMSA_RELEASE_005 = 'AHIMSA-RELEASE-005'
AHIMSA_RELEASE_006 = 'AHIMSA-RELEASE-006'
AHIMSA_RELEASE_007 = 'AHIMSA-RELEASE-007'
AHIMSA_CLI_001 = 'AHIMSA-CLI-001'
AHIMSA_CLI_002 = 'AHIMSA-CLI-002'

ALL_CODES = frozenset({
    'AHIMSA-RECIPE-001',
    'AHIMSA-RECIPE-002',
    'AHIMSA-RECIPE-003',
    'AHIMSA-RECIPE-004',
    'AHIMSA-APP-001',
    'AHIMSA-APP-002',
    'AHIMSA-APP-003',
    'AHIMSA-APP-004',
    'AHIMSA-MATIKA-001',
    'AHIMSA-MATIKA-002',
    'AHIMSA-PLUG-001',
    'AHIMSA-PLUG-002',
    'AHIMSA-PLUG-003',
    'AHIMSA-RESOLVE-001',
    'AHIMSA-RESOLVE-002',
    'AHIMSA-RESOLVE-003',
    'AHIMSA-RESOLVE-004',
    'AHIMSA-RESOLVE-005',
    'AHIMSA-RESOLVE-006',
    'AHIMSA-RESOLVE-007',
    'AHIMSA-RESOLVE-008',
    'AHIMSA-RESOLVE-009',
    'AHIMSA-RELEASE-001',
    'AHIMSA-RELEASE-002',
    'AHIMSA-RELEASE-003',
    'AHIMSA-RELEASE-004',
    'AHIMSA-RELEASE-005',
    'AHIMSA-RELEASE-006',
    'AHIMSA-RELEASE-007',
    'AHIMSA-CLI-001',
    'AHIMSA-CLI-002',
})

CODE_METADATA = {
    'AHIMSA-RECIPE-001': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RECIPE'},
    'AHIMSA-RECIPE-002': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RECIPE'},
    'AHIMSA-RECIPE-003': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RECIPE'},
    'AHIMSA-RECIPE-004': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RECIPE'},
    'AHIMSA-APP-001': {'severity': 'error', 'log_route': 'n/a', 'facility': 'APP'},
    'AHIMSA-APP-002': {'severity': 'error', 'log_route': 'n/a', 'facility': 'APP'},
    'AHIMSA-APP-003': {'severity': 'error', 'log_route': 'n/a', 'facility': 'APP'},
    'AHIMSA-APP-004': {'severity': 'error', 'log_route': 'n/a', 'facility': 'APP'},
    'AHIMSA-MATIKA-001': {'severity': 'error', 'log_route': 'n/a', 'facility': 'MATIKA'},
    'AHIMSA-MATIKA-002': {'severity': 'error', 'log_route': 'n/a', 'facility': 'MATIKA'},
    'AHIMSA-PLUG-001': {'severity': 'error', 'log_route': 'n/a', 'facility': 'PLUG'},
    'AHIMSA-PLUG-002': {'severity': 'error', 'log_route': 'n/a', 'facility': 'PLUG'},
    'AHIMSA-PLUG-003': {'severity': 'error', 'log_route': 'n/a', 'facility': 'PLUG'},
    'AHIMSA-RESOLVE-001': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RESOLVE'},
    'AHIMSA-RESOLVE-002': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RESOLVE'},
    'AHIMSA-RESOLVE-003': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RESOLVE'},
    'AHIMSA-RESOLVE-004': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RESOLVE'},
    'AHIMSA-RESOLVE-005': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RESOLVE'},
    'AHIMSA-RESOLVE-006': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RESOLVE'},
    'AHIMSA-RESOLVE-007': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RESOLVE'},
    'AHIMSA-RESOLVE-008': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RESOLVE'},
    'AHIMSA-RESOLVE-009': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RESOLVE'},
    'AHIMSA-RELEASE-001': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RELEASE'},
    'AHIMSA-RELEASE-002': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RELEASE'},
    'AHIMSA-RELEASE-003': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RELEASE'},
    'AHIMSA-RELEASE-004': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RELEASE'},
    'AHIMSA-RELEASE-005': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RELEASE'},
    'AHIMSA-RELEASE-006': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RELEASE'},
    'AHIMSA-RELEASE-007': {'severity': 'error', 'log_route': 'n/a', 'facility': 'RELEASE'},
    'AHIMSA-CLI-001': {'severity': 'fatal', 'log_route': 'n/a', 'facility': 'CLI'},
    'AHIMSA-CLI-002': {'severity': 'fatal', 'log_route': 'n/a', 'facility': 'CLI'},
}
